version: '3'
services:
  frontend:
    container_name: vader-flix-frontend
    image: node:16
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://192.168.50.92:3000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - /volume1/docker/projects/vader-flix-webapp/frontend:/app
    ports:
      - 3001:3000
    command: >
      bash -c "
        cd /app && 
        npm install && 
        npm start
      "