version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_VAR_TITLE=VaderFlix Dashboard
      - HOMEPAGE_VAR_APPLICATION_NAME=homepage
      - HOMEPAGE_ALLOWED_HOSTS=vaderflix.synology.me,portal.vaderflix.synology.me,dashboard.vaderflix.synology.me
    networks:
      - synobridge
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true

  vader-portal:
    build: ./portal
    container_name: vader-portal
    environment:
      - NODE_ENV=production
    volumes:
      - ./portal-data:/usr/src/app/data  # Mount data directory
    networks:
      - synobridge
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true

networks:
  synobridge:
    external: true