version: '3.8'

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - HOMEPAGE_VAR_TITLE=VaderFlix Dashboard
      - HOMEPAGE_VAR_APPLICATION_NAME=homepage
      - HOMEPAGE_ALLOWED_HOSTS=192.168.50.92:3000
    restart: unless-stopped
    # Synology specific settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # Ensure compatibility with Synology DSM 7.2.2
    security_opt:
      - no-new-privileges:true