# Quick access bookmarks (optional)
- Media Tools:
    - Plex:
        - href: https://vaderflix.synology.me
          icon: plex.png
    - Sonarr:
        - href: https://vaderflix.synology.me
          icon: sonarr.png  
    - Radarr:
        - href: https://vaderflix.synology.me
          icon: radarr.png