- Media Management:
    - Plex:
        href: https://vaderflix.synology.me/web
        icon: plex.png
        description: Media Server
        widget:
          type: plex
          url: https://vaderflix.synology.me
          key: KghtDhw7utRNszSA8k5n

    - Sonarr:
        href: https://vaderflix.synology.me/sonarr
        icon: sonarr.png
        description: TV Show Management
        widget:
          type: sonarr
          url: https://vaderflix.synology.me/sonarr
          key: 8709f14bd30d4924bc76349878a1a06f

    - Radarr:
        href: https://vaderflix.synology.me/radarr
        icon: radarr.png
        description: Movie Management
        widget:
          type: radarr
          url: https://vaderflix.synology.me/radarr
          key: 1796ecf4c4f244bfa6b7db47c6e271b0

    - Overseerr:
        href: https://vaderflix.synology.me
        icon: overseerr.png
        description: Request Management
        widget:
          type: overseerr
          url: https://vaderflix.synology.me
          key: MTc0NzY0ODMxOTM3NDc4NTdlYTEyLWNhN2YtNGRhYS05M2VkLTU5YzIyZWFmZDNkMQ==